import Foundation
import AppStoreConnector

// This key was generated by App Store Connect to make sure it has correct shape,
// but it has been revoked to make sure it‘s safe to commit.
enum SampleKey {
    static let pemString =
    "MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgwseAmqhyAPMALO1rbCDVbhn0M9tWGBVYJdVVx/aczkegCgYIKoZIzj0DAQehRANCAAR7BPlyY9GOG7V+yQlz84sRm7WIN4JU5XhcvyiECctnLHaS9sUYc43dMeNZ0qDBY7LPFiLiHqm3eUZj4xuH97HJ"
    
    static let pemStringWithDecodaration =
    """
    -----BEGIN PRIVATE KEY-----
    MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgwseAmqhyAPMALO1r
    bCDVbhn0M9tWGBVYJdVVx/aczkegCgYIKoZIzj0DAQehRANCAAR7BPlyY9GOG7V+
    yQlz84sRm7WIN4JU5XhcvyiECctnLHaS9sUYc43dMeNZ0qDBY7LPFiLiHqm3eUZj
    4xuH97HJ
    -----END PRIVATE KEY-----
    """
    
}
